---
- name: Join Windows Machine to Domain
  hosts: windows
  vars:
    domain_name: "your_domain_name"
    domain_admin_username: "your_admin_username"
    domain_admin_password: "your_admin_password"
  tasks:
    - name: Install Powershell Module for Domain Join
      win_shell: Install-Module -Name PSWindowsUpdate -Force -SkipPublisherCheck
      become: yes

    - name: Join Domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_name }}\\{{ domain_admin_username }}"
        domain_admin_password: "{{ domain_admin_password }}"
      become: yes

    - name: Restart Machine
      win_reboot:
        reboot_timeout: 120
        reboot_msg: "Joining the Domain, the machine will reboot in 120 seconds."
      become: yes

